apiVersion: batch/v1
kind: CronJob
metadata:
  name: scripy-web-ast02 # change team-id to your team e.g. wsl01
spec:
  schedule: "0 */6 * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scripy-web
            image: pattayaponsen/ast2:1
            imagePullPolicy: Always
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: ckan-token
                    key: token
              - name: CKAN_URL
                value: http://192.168.24.146
              - name: WEB_SCRIPY
                value: https://docs.google.com/spreadsheets/d/e/2PACX-1vQlEs3FxFPwm-dpvU1YdsfRgsbfT9WdiXJHZm9kJgGTziPnk-y3TWtftbSbxj6Fe_g0NxYgqyVHTVU5/pubhtml?gid=1397577608&amp;single=true&amp;widget=true&amp;headers=false
            command:
            - python
            - scripy.py
          restartPolicy: OnFailure
